name: Python Test

on:
  pull_request:
    branches:
      - main  # This triggers the action when there's a pull request to the main branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code from the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up Python
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Specifies which version of Python to use

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip  # Upgrade pip to the latest version

    # Step 4: Run the unit tests
    - name: Run unit tests
      run: |
        python -m unittest discover -s tests -p "*.py"  # Specify the directory and pattern for test discovery
